repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
        -   id: no-commit-to-branch
            name: Don't commit to master
        -   id: fix-encoding-pragma
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.7.0
        hooks:
        -   id: isort
            additional_dependencies: [toml]
            # excludes all the init files from sorting
            exclude: ^.*\/__init__\.py$
    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        -   id: black
    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.8.4
        hooks:
        -   id: flake8
