repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: fix-encoding-pragma
        -   id: flake8
        -   id: no-commit-to-branch
            name: Don't commit to master
    -   repo: https://github.com/psf/black
        rev: 19.3b0
        hooks:
        -   id: black
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
            - id: isort
    -   repo: https://github.com/asottile/add-trailing-comma
        rev: v1.5.0
        hooks:
        -   id: add-trailing-comma
